config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  devise_for :users

  resources :users, only: [:show] do
    resources :articles, only: [:index, :destroy]
  end
  
  resources :articles

  get '/search' => 'article#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    # @articles = fetch_top_headlines(params[:query])
    @articles = fetch_articles_testing
  end

  def create
    @article = Article.new(params[:article_params])
  end
  
  def destroy; end

  private

  def fetch_top_headlines(query)
    if query == '' || query == nil
      response = HTTP.headers(:'X-Api-Key' => "#{ENV["NEWS_API_KEY"]}").get("https://newsapi.org/v2/top-headlines?country=us")
    else
      response = HTTP.headers(:'X-Api-Key' => "#{ENV["NEWS_API_KEY"]}").get("https://newsapi.org/v2/top-headlines?q=#{query}")
    end

    return nil if response.status != 200
    JSON.parse(response)['articles']
  end

  def fetch_articles_testing
    response = [
      {
        "source"=>{"id"=>nil, "name"=>"YouTube"}, 
        "author"=>nil,
        "title"=>"Florida defender throws cleat in wild ending vs. LSU | 2020 College Football Highlights - ESPN","description"=>"With two minutes to go in a tied game, Florida's Marco Wilson gets hit with an unsportsmanlike conduct penalty as he throws the cleat of LSU’s Kole Taylor ac...",
        "url"=>"https://www.youtube.com/watch?v=Fif3Rkl5_nQ",
        "urlToImage"=>"https://i.ytimg.com/vi/Fif3Rkl5_nQ/maxresdefault.jpg",
        "publishedAt"=>"2020-12-13T06:11:10Z",
        "content"=>nil
      },
      {
        "source"=>{"id"=>nil, "name"=>"YouTube"}, 
        "author"=>nil,
        "title"=>"Florida defender throws cleat in wild ending vs. LSU | 2020 College Football Highlights - ESPN","description"=>"With two minutes to go in a tied game, Florida's Marco Wilson gets hit with an unsportsmanlike conduct penalty as he throws the cleat of LSU’s Kole Taylor ac...",
        "url"=>"https://www.youtube.com/watch?v=Fif3Rkl5_nQ",
        "urlToImage"=>"https://i.ytimg.com/vi/Fif3Rkl5_nQ/maxresdefault.jpg",
        "publishedAt"=>"2020-12-13T06:11:10Z",
        "content"=>nil
      },
      {
        "source"=>{"id"=>nil, "name"=>"YouTube"}, 
        "author"=>nil,
        "title"=>"Florida defender throws cleat in wild ending vs. LSU | 2020 College Football Highlights - ESPN","description"=>"With two minutes to go in a tied game, Florida's Marco Wilson gets hit with an unsportsmanlike conduct penalty as he throws the cleat of LSU’s Kole Taylor ac...",
        "url"=>"https://www.youtube.com/watch?v=Fif3Rkl5_nQ",
        "urlToImage"=>"https://i.ytimg.com/vi/Fif3Rkl5_nQ/maxresdefault.jpg",
        "publishedAt"=>"2020-12-13T06:11:10Z",
        "content"=>nil
      }
    ]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @articles = current_user.articles
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params(article)
    {
      image_url: article['urlToImage']
      title: article['title']
      description: article['description']
      source: article['source']['name']
    }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_article_search_form.html.erb
<%= form_with(url: articles_path, method: 'get', local: true) do |form| %>
  <%= form.label :query, 'Search by keyword' %>
  <%= form.text_field :query, placeholder: 'Eg. Football'%>
  <%= form.button 'Search'%>
<% end %>

app/views/articles/index.html.erb
<ul class="article-container">
  <% @articles.each do |article| %>
    <img src="<%= article['urlToImage']%>" alt="" class="thumbnail">
    <li class="article">
      <strong>
        <%= link_to article['title'], article['url'], target: '_blank', rel: 'noopener noreferrer' %>
      </strong>
      <br><br>
      <p><%= article['description'] %></p>
      <div class="publisher"><%= article['source']['name'] %></div>
      <%= button_to '+', new_article_path, params: article_params(article) %>
    </li>
    <hr>
  <% end %>
</ul>

app/views/layouts/_navbar.html.erb
<ul class="nav">
  <li>Driscoll News</li>
  <li><%= link_to 'Top Stories', articles_path %></li>
  <li><%= link_to 'Home', '/' %></li>
  <li class="article-search"><%= render 'article_search_form' %></li>
  <% if current_user %>
    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    <li><%= link_to 'Sign In', new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Driscoll News</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/home.html.erb
<h1>Driscoll News Homepage</h1>